const ARTICLES = Object.freeze({
    ADD_ARTICLE: 'ADD_ARTICLE',
    REMOVE_ARTICLE: 'REMOVE_ARTICLE',
    SET_VISIBLE: 'SET_VISIBLE',
    FETCH_ARTICLES_PENDING: 'FETCH_ARTICLES_PENDING',
    FETCH_ARTICLES_SUCCESS: 'FETCH_ARTICLES_SUCCESS',
    FETCH_ARTICLES_ERROR: 'FETCH_ARTICLES_ERROR'
})

export const TYPES = Object.freeze({
    ...ARTICLES
})